### PR TITLE
Rudimentary CoffeeScript support.

### PR DESCRIPTION
**Pull request by ezzatron**
As of 1.2, CouchDB has native CoffeeScript support. This PR adds basic support for CoffeeScript to couchdb-compile.

### CODE REVIEW

**Comment by jo** [comment]
Thank you very much for this pull!

Two questions:
- why is this _Rudimentary CoffeeScript support_ and what is needed to make it full?
- could you please have a look at the tests - why do they fail?

**Comment by ezzatron** [comment]
Sorry, I guess I was only running the compile tests locally. All tests now pass.

I suppose "rudimentary" is not entirely accurate. I wasn't super happy with my code, and figured you'd probably want to clean it up a bit before pulling, especially with regards to `useIndex()`, where I essentially just copy-pasted the existing function body inside itself to look for CoffeeScript module indexes. I just needed something that would get us by for now at my work, as this PR does.

To make it more solid, I would probably expect to see support for arbitrary languages, not just JS and CS, given that you *can* use just about any language with CouchDB (as long as you have the language server to support it).

Perhaps something in the options could add additional filename extensions to check for when looking for module indexes. That way you could probably support TypeScript, IcedCoffeeScript, etc. etc.

In any case, since CS support is now native in CouchDB, I felt that should probably just work out of the box here.

**Comment by jo** [comment]
Hey @ezzatron I am so sorry, I totally forgot your pr and changed the code according to [standard](https://www.npmjs.com/package/standard), which lead to thousand merge conflicts. Could I kindly ask you to rebase your branch?

**Comment by ezzatron** [comment]
@jo No worries, I can't tackle it right now, but I'll take a look a it soon.

**Comment by ezzatron** [comment]
Sorry it's been so long. I ended up writing my own similar library to tackle my use case better. If you're interested in the challenged I ran into while trying to use `couchdb-compile`, I wrote a little summary of the [differences](https://github.com/eloquent/couchdb-builder#differences-to-couchdb-compile) between the two libraries.

**Pull request closed without merging**
